# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalogue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'catalogue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61talogue.proto\x12\x12\x61pp.grpc.catalogue\"\x07\n\x05\x45mpty\"\x1c\n\x0eGetItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\rSearchRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"z\n\x11\x43reateItemRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x16\n\x0estarting_price\x18\x03 \x01(\x01\x12\x16\n\x0e\x64uration_hours\x18\x04 \x01(\x05\x12\x11\n\tseller_id\x18\x05 \x01(\x05\"\x9c\x02\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x16\n\x0estarting_price\x18\x04 \x01(\x05\x12\x15\n\rcurrent_price\x18\x05 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x08\x12\x16\n\x0e\x64uration_hours\x18\x07 \x01(\x05\x12\x12\n\ncreated_at\x18\x08 \x01(\t\x12\x10\n\x08\x65nd_time\x18\t \x01(\t\x12\x11\n\tseller_id\x18\n \x01(\x05\x12\x1e\n\x16remaining_time_seconds\x18\x0b \x01(\x05\x12\x15\n\rshipping_cost\x18\x0c \x01(\x05\x12\x15\n\rshipping_time\x18\r \x01(\x05\";\n\x08ItemList\x12/\n\x05items\x18\x01 \x03(\x0b\x32 .app.grpc.catalogue.ItemResponse2\xd2\x02\n\x10\x43\x61talogueService\x12\x46\n\x0bGetAllItems\x12\x19.app.grpc.catalogue.Empty\x1a\x1c.app.grpc.catalogue.ItemList\x12N\n\x0bSearchItems\x12!.app.grpc.catalogue.SearchRequest\x1a\x1c.app.grpc.catalogue.ItemList\x12U\n\nCreateItem\x12%.app.grpc.catalogue.CreateItemRequest\x1a .app.grpc.catalogue.ItemResponse\x12O\n\x07GetItem\x12\".app.grpc.catalogue.GetItemRequest\x1a .app.grpc.catalogue.ItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalogue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=39
  _globals['_EMPTY']._serialized_end=46
  _globals['_GETITEMREQUEST']._serialized_start=48
  _globals['_GETITEMREQUEST']._serialized_end=76
  _globals['_SEARCHREQUEST']._serialized_start=78
  _globals['_SEARCHREQUEST']._serialized_end=110
  _globals['_CREATEITEMREQUEST']._serialized_start=112
  _globals['_CREATEITEMREQUEST']._serialized_end=234
  _globals['_ITEMRESPONSE']._serialized_start=237
  _globals['_ITEMRESPONSE']._serialized_end=521
  _globals['_ITEMLIST']._serialized_start=523
  _globals['_ITEMLIST']._serialized_end=582
  _globals['_CATALOGUESERVICE']._serialized_start=585
  _globals['_CATALOGUESERVICE']._serialized_end=923
# @@protoc_insertion_point(module_scope)
