# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalogue_pb2 as catalogue__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in catalogue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllItems = channel.unary_unary(
                '/app.grpc.catalogue.CatalogueService/GetAllItems',
                request_serializer=catalogue__pb2.Empty.SerializeToString,
                response_deserializer=catalogue__pb2.ItemList.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/app.grpc.catalogue.CatalogueService/SearchItems',
                request_serializer=catalogue__pb2.SearchRequest.SerializeToString,
                response_deserializer=catalogue__pb2.ItemList.FromString,
                _registered_method=True)
        self.CreateItem = channel.unary_unary(
                '/app.grpc.catalogue.CatalogueService/CreateItem',
                request_serializer=catalogue__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=catalogue__pb2.ItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/app.grpc.catalogue.CatalogueService/GetItem',
                request_serializer=catalogue__pb2.GetItemRequest.SerializeToString,
                response_deserializer=catalogue__pb2.ItemResponse.FromString,
                _registered_method=True)


class CatalogueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllItems,
                    request_deserializer=catalogue__pb2.Empty.FromString,
                    response_serializer=catalogue__pb2.ItemList.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=catalogue__pb2.SearchRequest.FromString,
                    response_serializer=catalogue__pb2.ItemList.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=catalogue__pb2.CreateItemRequest.FromString,
                    response_serializer=catalogue__pb2.ItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=catalogue__pb2.GetItemRequest.FromString,
                    response_serializer=catalogue__pb2.ItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.catalogue.CatalogueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.grpc.catalogue.CatalogueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.catalogue.CatalogueService/GetAllItems',
            catalogue__pb2.Empty.SerializeToString,
            catalogue__pb2.ItemList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.catalogue.CatalogueService/SearchItems',
            catalogue__pb2.SearchRequest.SerializeToString,
            catalogue__pb2.ItemList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.catalogue.CatalogueService/CreateItem',
            catalogue__pb2.CreateItemRequest.SerializeToString,
            catalogue__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.catalogue.CatalogueService/GetItem',
            catalogue__pb2.GetItemRequest.SerializeToString,
            catalogue__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
